Sajonia_allFeatures
jrolana/benkyou pull request #21
Opened 2024-05-21 19:30 UTC by KJCSajonia

2024-05-21 21:23 UTC, KJCSajonia commented
![Screenshot (133)](https://github.com/jrolana/benkyou/assets/125939107/70331673-7113-4ac9-a654-3c278ef21f45)

2024-05-21 21:24 UTC, KJCSajonia commented
![Screenshot (133)](https://github.com/jrolana/benkyou/assets/125939107/f42da58b-62b7-4825-8a9c-a599b767b85f)

2024-05-21 21:25 UTC, KJCSajonia commented
![Uploading Screenshot (132).png…]()

2024-05-21 21:26 UTC, KJCSajonia commented
![Uploading Screenshot (132).png…]()

2024-05-21 21:26 UTC, KJCSajonia commented
[
![Screenshot (132)](https://github.com/jrolana/benkyou/assets/125939107/26623448-c32e-436a-81c6-914e9311e5a2)
](url)

2024-05-22 07:36 UTC, jrolana requested changes

2024-05-22 07:36 UTC, jrolana commented on HomePage.html
- ang html filename and javascript is iba, pachange na lang to homepage
- sa add event part iba ang design sa figma, may new workway ka na how to add an event ba?

2024-05-22 07:36 UTC, jrolana commented on styles/LandingPage.css
- ang html filename and css is iba, pachange na lang to landingpage
- because of the filename di siya gareflect maayos on my end
- 
![image](https://github.com/jrolana/benkyou/assets/113810517/9572b268-bcd2-4606-bb03-c246ea2848c4)
![image](https://github.com/jrolana/benkyou/assets/113810517/51f32f77-9f22-40ff-aa22-03c890312387)

2024-05-22 08:39 UTC, KJCSajonia commented on HomePage.html
Helloo, na changee ko na ang file, nilagayy ko na styles\homepage.css att styles\LandingPage.css peroo not sure if tama siya tho. Lemmee know langg if di pa rin siya gumagana

sa add event na partt, itryy ko muna ang google calendar services na api if okayy siya and free langg, pero if hindi plan ko is magawa na lang ng database ng events sa php where may separate na forms na ilagay ang mga user to add mga eventsss 

Thankk u!

2024-05-22 08:47 UTC, KJCSajonia commented on HomePage.html
btww sa may js palaa, placeholderr lang muna siya hehe, mayy itryy pa kasi ako sa calendarr so di ko muna sinend angg filee hehe

2024-05-22 09:24 UTC, merged